package com.sondeos.javanotifychallenge.repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NotificationRepository {

    private static Map<String, String> createNotification(String contactId, String type, String message) {
        Map<String, String> notification = new HashMap<>();
        notification.put("contactId", contactId);
        notification.put("type", type);
        notification.put("message", message);
        return notification;
    }

   static public List<Map<String, String>> getNotifications(){

       List<Map<String, String>> notification = List.of(

               createNotification("24", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("6", "sms", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("18", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("9", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("9", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("7", "email", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("13", "sms", "Tu pedido ha sido enviado y llegará pronto."),
               createNotification("14", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("8", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("20", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("3", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("25", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("9", "sms", "¡Oferta especial solo por hoy!"),
               createNotification("22", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("25", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("15", "sms", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("25", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("17", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("14", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("15", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("14", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("18", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("8", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("13", "sms", "Tu pedido ha sido enviado y llegará pronto."),
               createNotification("13", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("16", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("15", "email", "¡Oferta especial solo por hoy!"),
               createNotification("20", "email", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("21", "sms", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("11", "email", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("9", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("14", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("15", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("9", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("10", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("16", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("19", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("23", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("46", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("2", "sms", "¡Oferta especial solo por hoy!"),
               createNotification("13", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("1", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("12", "sms", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("25", "sms", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("19", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("12", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("2", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("13", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("15", "sms", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("23", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("3", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("20", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("15", "sms", "¡Oferta especial solo por hoy!"),
               createNotification("24", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("4", "sms", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("23", "email", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("22", "sms", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("18", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("19", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("23", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("24", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("25", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("22", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("7", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("6", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("19", "email", "¡Oferta especial solo por hoy!"),
               createNotification("16", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("10", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("11", "sms", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("16", "sms", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("25", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("21", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("7", "sms", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("14", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("13", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("15", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("8", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("24", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("15", "email", "¡Oferta especial solo por hoy!"),
               createNotification("22", "email", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("10", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("7", "email", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("21", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("3", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("20", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("7", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("15", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("14", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("21", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("7", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("25", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("19", "sms", "¡Oferta especial solo por hoy!"),
               createNotification("15", "email", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("11", "sms", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("14", "sms", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("15", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("14", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("2", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("18", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("2", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("5", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("12", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("3", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("20", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("7", "email", "¡Oferta especial solo por hoy!"),
               createNotification("18", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("25", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("11", "sms", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("21", "email", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("5", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("9", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("13", "sms", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("2", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("21", "sms", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("18", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("10", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("16", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("19", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("22", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("6", "sms", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("11", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("11", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("8", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("12", "sms", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("24", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("14", "sms", "Tu cuenta ha sido actualizada con éxito."),
               createNotification("16", "email", "Recuerda que tu cita es mañana a las 10 AM."),
               createNotification("4", "sms", "¡Oferta especial solo por hoy!"),
               createNotification("13", "email", "¡Nuevas funciones disponibles en nuestra aplicación!"),
               createNotification("25", "sms", "Hemos detectado un inicio de sesión desde un nuevo dispositivo."),
               createNotification("11", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("8", "sms", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("9", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("18", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("9", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("1", "sms", "¡Obtén un 20% de descuento en tu próxima compra!"),
               createNotification("24", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("15", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("19", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("15", "sms", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("7", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("16", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("20", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("14", "sms", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("22", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("23", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("13", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("21", "sms", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("9", "email", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("10", "sms", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("25", "email", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("19", "sms", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("8", "email", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("13", "sms", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("22", "email", "No olvides revisar tu progreso en el desafío."),
               createNotification("12", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("16", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("7", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("16", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("18", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("24", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("21", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("5", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("11", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("3", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("15", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("14", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("12", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("15", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("8", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("4", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("6", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("15", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("16", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("2", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("18", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("7", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("16", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("1", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("20", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("20", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("13", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("19", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("24", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("25", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("11", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("15", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("18", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("6", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("13", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("2", "sms", "Recuerda que tu suscripción se renueva mañana."),
               createNotification("8", "email", "¡Felicitaciones! Has ganado un cupón de regalo."),
               createNotification("13", "sms", "¡Gracias por ser parte de nuestra comunidad!"),
               createNotification("25", "email", "Tu cuenta ha sido bloqueada por actividad sospechosa."),
               createNotification("21", "sms", "No olvides revisar tu progreso en el desafío."),
               createNotification("14", "email", "¡Participa en nuestro concurso para ganar premios!"),
               createNotification("4", "sms", "Hemos actualizado nuestros términos y condiciones."),
               createNotification("10", "email", "Tu sesión ha expirado, por favor inicia sesión nuevamente."),
               createNotification("9", "sms", "Recuerda que tu suscripción se renueva mañana.")
                      ); return notification;
   }

}
