package com.sondeos.javanotifychallenge.repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NotificationRepository {

    private static Map<String, String> createNotification(String contactId, String type, String message) {
        Map<String, String> notification = new HashMap<>();
        notification.put("contactId", contactId);
        notification.put("type", type);
        notification.put("message", message);
        return notification;
    }

   static public Iterable<Map<String, String>> getNotifications(){

       return List.of(
               createNotification("44", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("6", "sms", "Your updates from Java Notify Challenge!"),
               createNotification("37", "sms", "Hello from Java Notify Challenge!"),
               createNotification("9", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("9", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("7", "email", "Your updates from Java Notify Challenge!"),
               createNotification("13", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("14", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("8", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("40", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("3", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("45", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("9", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("22", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("25", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("15", "sms", "Hello from Java Notify Challenge!"),
               createNotification("25", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("18", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("14", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("15", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("14", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("37", "email", "Great job in the Java Notify Challenge!"),
               createNotification("28", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("13", "sms", "Hello from Java Notify Challenge!"),
               createNotification("13", "sms", "Hi from Java Notify Challenge!"),
               createNotification("16", "email", "Your updates from Java Notify Challenge!"),
               createNotification("15", "email", "Hello from Java Notify Challenge!"),
               createNotification("40", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("21", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("11", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("9", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("34", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("15", "sms", "The Java Notify Challenge is designed to test not only your skills but your patience and persistence. You've shown incredible resolve, and we encourage you to continue pushing your limits."),
               createNotification("9", "email", "Good morning from Java Notify Challenge!"),
               createNotification("30", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("26", "email", "Good morning from Java Notify Challenge!"),
               createNotification("19", "email", "Your updates from Java Notify Challenge!"),
               createNotification("23", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("17", "email", "Hi from Java Notify Challenge!"),
               createNotification("2", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("23", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("1", "email", "Welcome to Java Notify Challenge!"),
               createNotification("32", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("25", "sms", "Hi from Java Notify Challenge!"),
               createNotification("30", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("32", "email", "You are notified by Java Notify Challenge!"),
               createNotification("2", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("33", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("35", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("23", "sms", "Hi from Java Notify Challenge!"),
               createNotification("3", "email", "Hi from Java Notify Challenge!"),
               createNotification("8", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("35", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("45", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("44", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("4", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("43", "email", "A quick update from Java Notify Challenge!"),
               createNotification("42", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("38", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("39", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("43", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("44", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("25", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("42", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("7", "sms", "We are proud of your progress in the Java Notify Challenge! Each notification is a reminder of your relentless pursuit of success. Don’t stop now; you're closer than you think!"),
               createNotification("6", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("39", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("36", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("10", "email", "You are notified by Java Notify Challenge!"),
               createNotification("31", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("26", "sms", "You are notified by Java Notify Challenge!"),
               createNotification("45", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("41", "sms", "Hi from Java Notify Challenge!"),
               createNotification("7", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("34", "email", "Good morning from Java Notify Challenge!"),
               createNotification("13", "email", "Hello from Java Notify Challenge!"),
               createNotification("35", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("8", "sms", "Hello from Java Notify Challenge!"),
               createNotification("23", "email", "In the Java Notify Challenge, consistency is key, and you've demonstrated that trait beautifully. Your journey is inspiring, and we can't wait to see the final outcome of all your hard work."),
               createNotification("15", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("22", "email", "Hi from Java Notify Challenge!"),
               createNotification("10", "email", "Good morning from Java Notify Challenge!"),
               createNotification("7", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("21", "email", "Welcome to Java Notify Challenge!"),
               createNotification("3", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("20", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("27", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("15", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("34", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Keep up the good work in Java Notify Challenge!"),
               createNotification("27", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("45", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("39", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("15", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("31", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("34", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("35", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("2", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("37", "email", "Good morning from Java Notify Challenge!"),
               createNotification("2", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("5", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("12", "sms", "Hello from Java Notify Challenge!"),
               createNotification("3", "email", "Welcome to Java Notify Challenge!"),
               createNotification("20", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("7", "email", "Hi from Java Notify Challenge!"),
               createNotification("18", "sms", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("25", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("30", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("41", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("5", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("9", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("13", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("2", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("21", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("38", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("10", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("16", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("19", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("22", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("6", "sms", "Hi from Java Notify Challenge!"),
               createNotification("11", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("31", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("28", "email", "Good morning from Java Notify Challenge!"),
               createNotification("32", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("24", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("14", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("36", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("4", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("33", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("45", "sms", "Hi from Java Notify Challenge!"),
               createNotification("17", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("8", "sms", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("23", "email", "Great job in the Java Notify Challenge!"),
               createNotification("37", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("29", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("1", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("44", "email", "Good morning from Java Notify Challenge!"),
               createNotification("15", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("39", "email", "Hi from Java Notify Challenge!"),
               createNotification("35", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("27", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("26", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("40", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("34", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("42", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("43", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("12", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Hi from Java Notify Challenge!"),
               createNotification("9", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("10", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("25", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("19", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("8", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("13", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("22", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("32", "email", "Your journey through the Java Notify Challenge is nothing short of incredible. The dedication and passion you’ve shown are exactly what it takes to succeed in this competitive environment."),
               createNotification("30", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("7", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("16", "sms", "Hi from Java Notify Challenge!"),
               createNotification("18", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("24", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("41", "email", "A quick update from Java Notify Challenge!"),
               createNotification("5", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("11", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("3", "sms", "Hi from Java Notify Challenge!"),
               createNotification("15", "email", "Good morning from Java Notify Challenge!"),
               createNotification("14", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("32", "email", "Welcome to Java Notify Challenge!"),
               createNotification("35", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("28", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("4", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("6", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("23", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("36", "email", "Hi from Java Notify Challenge!"),
               createNotification("2", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("38", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("27", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("26", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("1", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("20", "email", "Great job in the Java Notify Challenge!"),
               createNotification("40", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("33", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("39", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("44", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("45", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("31", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("15", "sms", "Hello from the Java Notify Challenge!"),
               createNotification("23", "email", "Great job in the Java Notify Challenge!"),
               createNotification("6", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("33", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("2", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("28", "email", "You are doing great in the Java Notify Challenge!"),
               createNotification("12", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("45", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("41", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("4", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("30", "email", "Your progress is amazing in the Java Notify Challenge!"),
               createNotification("9", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("17", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("26", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("44", "email", "Thank you for being an essential part of the Java Notify Challenge. Every step you've taken in this challenge is leading you towards your ultimate goal. Keep up the momentum!"),
               createNotification("7", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("40", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("20", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("10", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("5", "email", "You are doing great in the Java Notify Challenge!"),
               createNotification("31", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("16", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("34", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("39", "email", "Great job in the Java Notify Challenge!"),
               createNotification("18", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("25", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("22", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("36", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("19", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("13", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("8", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("37", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("3", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("44", "email", "Keep up the great work in the Java Notify Challenge!"),
               createNotification("27", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("35", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("11", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("24", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("42", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("29", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("38", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("36", "sms", "As part of the Java Notify Challenge, you’ve proven time and again that hard work and perseverance yield remarkable results. Keep your eyes on the prize and continue to give your best!"),
               createNotification("32", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("1", "email", "Hi from the Java Notify Challenge!"),
               createNotification("43", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("12", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("28", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("7", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("30", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("15", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("4", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("17", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("14", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("35", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("25", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("9", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("11", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("40", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("23", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("31", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("20", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("6", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("43", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("41", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("2", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("26", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("13", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("45", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("22", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("10", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("19", "email", "Your commitment to the Java Notify Challenge is impressive! Every action you take brings you closer to the goal, and the effort you're putting in is a testament to your determination."),
               createNotification("18", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("33", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("39", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("24", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("5", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("32", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("3", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("8", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("27", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("36", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("16", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("38", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("19", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("34", "email", "Hi from the Java Notify Challenge!"),
               createNotification("29", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("1", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("42", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("10", "sms", "Hello from the Java Notify Challenge!"),
               createNotification("8", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("22", "sms", "You are doing great in the Java Notify Challenge!"),
               createNotification("15", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("32", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("44", "email", "Great job in the Java Notify Challenge!"),
               createNotification("11", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("35", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("19", "sms", "Keep up the great work in the Java Notify Challenge!"),
               createNotification("6", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("29", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("24", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("17", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("3", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("25", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("41", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("2", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("40", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("33", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("5", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("9", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("14", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("1", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("28", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("37", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("18", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("7", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("28", "sms", "The Java Notify Challenge is a journey of persistence, dedication, and passion. You've shown all these qualities and more. Continue this path, and the results will speak for themselves."),
               createNotification("43", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("12", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("39", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("16", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("4", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("36", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("27", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("23", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("21", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("42", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("20", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("34", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("13", "email", "Great job in the Java Notify Challenge!"),
               createNotification("26", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("31", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("45", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("30", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("38", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("11", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("24", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("14", "email", "Hi from the Java Notify Challenge!"),
               createNotification("22", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("6", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("28", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("9", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("19", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("5", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("17", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("10", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("33", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("8", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("29", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("15", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("40", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("5", "email", "Congratulations on your participation in the Java Notify Challenge! Your efforts have been truly inspiring, and we are thrilled to see how far you've come. Keep up the fantastic work!"),
               createNotification("2", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("3", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("21", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("13", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("31", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("4", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("20", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("44", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("39", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("25", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("7", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("27", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("16", "email", "Hi from the Java Notify Challenge!"),
               createNotification("41", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("30", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("12", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("37", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("18", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("34", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("1", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("26", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("35", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("36", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("32", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("43", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("45", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("3", "sms", "Hello from the Java Notify Challenge!"),
               createNotification("10", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("23", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("44", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("16", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("35", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("12", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("28", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("21", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("41", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("7", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("33", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("9", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("25", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("39", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("45", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("4", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("31", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("24", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("20", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("1", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("30", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("18", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("17", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("36", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("2", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("11", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("27", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("38", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("19", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("22", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("42", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("29", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("8", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("34", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("15", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("6", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("43", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("13", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("5", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("26", "email", "Hi from the Java Notify Challenge!"),
               createNotification("40", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("37", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("32", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("28", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("12", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("9", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("44", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("18", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("14", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("3", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("23", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("41", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("11", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("35", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("7", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("20", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("19", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("31", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("2", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("40", "email", "Hi from the Java Notify Challenge!"),
               createNotification("13", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("10", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("27", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("12", "sms", "We are excited to inform you that the Java Notify Challenge has reached new heights! Keep pushing forward, as your progress is amazing, and the results are even better!"),
               createNotification("15", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("22", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("33", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("6", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("17", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("45", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("24", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("5", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("8", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("30", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("37", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("16", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("4", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("42", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("34", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("38", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("21", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("36", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("29", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("5", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("17", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("33", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("24", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("39", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("12", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("35", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("21", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("1", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("43", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("30", "email", "Hi from the Java Notify Challenge!"),
               createNotification("9", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("11", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("18", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("32", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("26", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("3", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("45", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("22", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("28", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("4", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("10", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("31", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("15", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("20", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("40", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("36", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("7", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("19", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("25", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("6", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("34", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("2", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("27", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("16", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("38", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("13", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("42", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("41", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("23", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("8", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("44", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("5", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("29", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("37", "email", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("9", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("33", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("14", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("30", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("12", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("17", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("40", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("21", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("3", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("28", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("19", "sms", "Good morning from the Java Notify Challenge!"),
               createNotification("26", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("10", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("24", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("31", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("11", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("45", "sms", "You're making great progress in the Java Notify Challenge!"),
               createNotification("36", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("4", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("18", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("22", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("39", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("13", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("15", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("6", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("27", "email", "You're making great progress in the Java Notify Challenge!"),
               createNotification("16", "sms", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("35", "email", "Good morning from the Java Notify Challenge!"),
               createNotification("41", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("2", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("34", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("7", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("20", "sms", "Keep up the good work in the Java Notify Challenge!"),
               createNotification("38", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("8", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("32", "email", "Notification successfully sent from the Java Notify Challenge!"),
               createNotification("42", "sms", "Welcome to the Java Notify Challenge!"),
               createNotification("23", "email", "Java Notify Challenge appreciates your effort!")
               );
   }

}
