package com.sondeos.javanotifychallenge.repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NotificationRepository {

    private static Map<String, String> createNotification(String contactId, String type, String message) {
        Map<String, String> notification = new HashMap<>();
        notification.put("contactId", contactId);
        notification.put("type", type);
        notification.put("message", message);
        return notification;
    }

   static public List<Map<String, String>> getNotifications(){

       return List.of(
               createNotification("24", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("6", "sms", "Your updates from Java Notify Challenge!"),
               createNotification("18", "sms", "Hello from Java Notify Challenge!"),
               createNotification("9", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("9", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("7", "email", "Your updates from Java Notify Challenge!"),
               createNotification("13", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("14", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("8", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("20", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("3", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("25", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("9", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("22", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("25", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("15", "sms", "Hello from Java Notify Challenge!"),
               createNotification("25", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("17", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("14", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("15", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("14", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("18", "email", "Great job in the Java Notify Challenge!"),
               createNotification("8", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("13", "sms", "Hello from Java Notify Challenge!"),
               createNotification("13", "sms", "Hi from Java Notify Challenge!"),
               createNotification("16", "email", "Your updates from Java Notify Challenge!"),
               createNotification("15", "email", "Hello from Java Notify Challenge!"),
               createNotification("20", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("21", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("11", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("9", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("14", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("15", "sms", "The Java Notify Challenge is designed to test not only your skills but your patience and persistence. You've shown incredible resolve, and we encourage you to continue pushing your limits."),
               createNotification("9", "email", "Good morning from Java Notify Challenge!"),
               createNotification("10", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("16", "email", "Good morning from Java Notify Challenge!"),
               createNotification("19", "email", "Your updates from Java Notify Challenge!"),
               createNotification("23", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("46", "email", "Hi from Java Notify Challenge!"),
               createNotification("2", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("13", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("1", "email", "Welcome to Java Notify Challenge!"),
               createNotification("12", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("25", "sms", "Hi from Java Notify Challenge!"),
               createNotification("19", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("12", "email", "You are notified by Java Notify Challenge!"),
               createNotification("2", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("13", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("15", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("23", "sms", "Hi from Java Notify Challenge!"),
               createNotification("3", "email", "Hi from Java Notify Challenge!"),
               createNotification("20", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("15", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("25", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("24", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("4", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("23", "email", "A quick update from Java Notify Challenge!"),
               createNotification("22", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("18", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("19", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("23", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("24", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("25", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("22", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("7", "sms", "We are proud of your progress in the Java Notify Challenge! Each notification is a reminder of your relentless pursuit of success. Don’t stop now; you're closer than you think!"),
               createNotification("6", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("19", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("16", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("10", "email", "You are notified by Java Notify Challenge!"),
               createNotification("11", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("16", "sms", "You are notified by Java Notify Challenge!"),
               createNotification("25", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Hi from Java Notify Challenge!"),
               createNotification("7", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("14", "email", "Good morning from Java Notify Challenge!"),
               createNotification("13", "email", "Hello from Java Notify Challenge!"),
               createNotification("15", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("8", "sms", "Hello from Java Notify Challenge!"),
               createNotification("24", "email", "In the Java Notify Challenge, consistency is key, and you've demonstrated that trait beautifully. Your journey is inspiring, and we can't wait to see the final outcome of all your hard work."),
               createNotification("15", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("22", "email", "Hi from Java Notify Challenge!"),
               createNotification("10", "email", "Good morning from Java Notify Challenge!"),
               createNotification("7", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("21", "email", "Welcome to Java Notify Challenge!"),
               createNotification("3", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("20", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("7", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("15", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("14", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Keep up the good work in Java Notify Challenge!"),
               createNotification("7", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("25", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("19", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("15", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("11", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("15", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("2", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("18", "email", "Good morning from Java Notify Challenge!"),
               createNotification("2", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("5", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("12", "sms", "Hello from Java Notify Challenge!"),
               createNotification("3", "email", "Welcome to Java Notify Challenge!"),
               createNotification("20", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("7", "email", "Hi from Java Notify Challenge!"),
               createNotification("18", "sms", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("25", "email", "You're doing great in the Java Notify Challenge!"),
               createNotification("11", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("21", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("5", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("9", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("13", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("2", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("21", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("18", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("10", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("16", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("19", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("22", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("6", "sms", "Hi from Java Notify Challenge!"),
               createNotification("11", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("11", "sms", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("8", "email", "Good morning from Java Notify Challenge!"),
               createNotification("12", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("24", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("14", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("16", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("4", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("13", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("25", "sms", "Hi from Java Notify Challenge!"),
               createNotification("11", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("8", "sms", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("9", "email", "Great job in the Java Notify Challenge!"),
               createNotification("18", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("9", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("1", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("24", "email", "Good morning from Java Notify Challenge!"),
               createNotification("15", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("19", "email", "Hi from Java Notify Challenge!"),
               createNotification("15", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("7", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("16", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("20", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("14", "sms", "Great progress in the Java Notify Challenge!"),
               createNotification("22", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("23", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("13", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("21", "sms", "Hi from Java Notify Challenge!"),
               createNotification("9", "email", "Notification successfully sent from Java Notify Challenge!"),
               createNotification("10", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("25", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("19", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("8", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("13", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("22", "email", "Great progress in the Java Notify Challenge!"),
               createNotification("12", "email", "Your journey through the Java Notify Challenge is nothing short of incredible. The dedication and passion you’ve shown are exactly what it takes to succeed in this competitive environment."),
               createNotification("16", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("7", "email", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("16", "sms", "Hi from Java Notify Challenge!"),
               createNotification("18", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("24", "sms", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("21", "email", "A quick update from Java Notify Challenge!"),
               createNotification("5", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("11", "email", "Keep going with the Java Notify Challenge!"),
               createNotification("3", "sms", "Hi from Java Notify Challenge!"),
               createNotification("15", "email", "Good morning from Java Notify Challenge!"),
               createNotification("14", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("12", "email", "Welcome to Java Notify Challenge!"),
               createNotification("15", "sms", "You're doing great in the Java Notify Challenge!"),
               createNotification("8", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("4", "sms", "Great job in the Java Notify Challenge!"),
               createNotification("6", "email", "We hope you enjoy the Java Notify Challenge!"),
               createNotification("15", "sms", "Good morning from Java Notify Challenge!"),
               createNotification("16", "email", "Hi from Java Notify Challenge!"),
               createNotification("2", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("18", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("7", "sms", "Don't forget to check your progress in the Java Notify Challenge!"),
               createNotification("16", "email", "Keep participating in the Java Notify Challenge!"),
               createNotification("1", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("20", "email", "Great job in the Java Notify Challenge!"),
               createNotification("20", "sms", "Welcome to Java Notify Challenge!"),
               createNotification("13", "email", "Java Notify Challenge appreciates your effort!"),
               createNotification("19", "sms", "A quick update from Java Notify Challenge!"),
               createNotification("24", "email", "Keep up the good work in Java Notify Challenge!"),
               createNotification("25", "sms", "Enjoy the Java Notify Challenge!"),
               createNotification("11", "email", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("15", "sms", "Hello from the Java Notify Challenge!"),
               createNotification("18", "email", "Great job in the Java Notify Challenge!"),
               createNotification("6", "sms", "Keep going with the Java Notify Challenge!"),
               createNotification("13", "email", "Welcome to the Java Notify Challenge!"),
               createNotification("2", "sms", "Thanks for participating in the Java Notify Challenge!"),
               createNotification("8", "email", "You are doing great in the Java Notify Challenge!"),
               createNotification("13", "sms", "Java Notify Challenge appreciates your effort!"),
               createNotification("25", "email", "Enjoy the Java Notify Challenge!"),
               createNotification("21", "sms", "Keep participating in the Java Notify Challenge!"),
               createNotification("14", "email", "Thanks for staying with the Java Notify Challenge!"),
               createNotification("4", "sms", "Hi from the Java Notify Challenge!"),
               createNotification("10", "email", "Your progress is amazing in the Java Notify Challenge!"),
               createNotification("9", "sms", "We hope you enjoy the Java Notify Challenge!")
               );
   }

}
